//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boolood.Resources.Fa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Boolood.Resources.Fa.ExceptionResource", typeof(ExceptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تصاویر متن اصلی از {0} عدد بیشتر است.
        /// </summary>
        public static string ArticleBodyInvalidImageCountException {
            get {
                return ResourceManager.GetString("ArticleBodyInvalidImageCountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه تصویر {0} ام متن اصلی از {1} کیلو بایت بیشتر است.
        /// </summary>
        public static string ArticleBodyInvalidImageSizeException {
            get {
                return ResourceManager.GetString("ArticleBodyInvalidImageSizeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه {0} مقاله از {1} کاراکتر بیشتر است.
        /// </summary>
        public static string ArticleTextInvalidLengthException {
            get {
                return ResourceManager.GetString("ArticleTextInvalidLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت تصویر{0} jpeg یا png باید باشد.
        /// </summary>
        public static string InvalidArticleImageFormatEcxeption {
            get {
                return ResourceManager.GetString("InvalidArticleImageFormatEcxeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تناسب طول و عرض تصویر {0} بین  {1} و {2}  نیست.
        /// </summary>
        public static string InvalidArticleImageRaitoException {
            get {
                return ResourceManager.GetString("InvalidArticleImageRaitoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه فایل تصویر {0} بیشتر از {1} کیلو بایت است.
        /// </summary>
        public static string InvalidArticleImageSizeException {
            get {
                return ResourceManager.GetString("InvalidArticleImageSizeException", resourceCulture);
            }
        }
    }
}
